-- Founder Sales Command. Additive, replay-safe CRM structures.
-- Historical stage, contact, and completion instants are not invented from updated_at.
-- Annotation of existing stage-history rows is migration-only because the table is immutable.

ALTER TABLE crm_stage_history ADD COLUMN IF NOT EXISTS event_kind TEXT;
ALTER TABLE crm_stage_history ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ;
ALTER TABLE crm_stage_history ADD COLUMN IF NOT EXISTS time_quality TEXT;
ALTER TABLE crm_stage_history ADD COLUMN IF NOT EXISTS event_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE crm_stage_history DROP CONSTRAINT IF EXISTS crm_stage_history_event_kind_check;
ALTER TABLE crm_stage_history ADD CONSTRAINT crm_stage_history_event_kind_check
  CHECK (event_kind IS NULL OR event_kind IN ('STAGE', 'INITIAL', 'REOPEN', 'BASELINE'));
ALTER TABLE crm_stage_history DROP CONSTRAINT IF EXISTS crm_stage_history_time_quality_check;
ALTER TABLE crm_stage_history ADD CONSTRAINT crm_stage_history_time_quality_check
  CHECK (time_quality IS NULL OR time_quality IN ('OBSERVED', 'UNKNOWN'));

ALTER TABLE crm_stage_history DISABLE TRIGGER stage_history_immutable;
UPDATE crm_stage_history
SET
  event_kind = CASE WHEN from_code IS NULL THEN 'BASELINE' ELSE 'STAGE' END,
  time_quality = CASE WHEN from_code IS NULL THEN 'UNKNOWN' ELSE 'OBSERVED' END,
  recorded_at = entered_at
WHERE event_kind IS NULL OR time_quality IS NULL OR recorded_at IS NULL;
ALTER TABLE crm_stage_history ENABLE TRIGGER stage_history_immutable;

ALTER TABLE crm_stage_history ALTER COLUMN event_kind SET DEFAULT 'STAGE';
ALTER TABLE crm_stage_history ALTER COLUMN time_quality SET DEFAULT 'UNKNOWN';
ALTER TABLE crm_stage_history ALTER COLUMN recorded_at SET DEFAULT now();
UPDATE crm_stage_history SET event_kind = 'STAGE' WHERE event_kind IS NULL;
UPDATE crm_stage_history SET time_quality = 'UNKNOWN' WHERE time_quality IS NULL;
UPDATE crm_stage_history SET recorded_at = entered_at WHERE recorded_at IS NULL;
ALTER TABLE crm_stage_history ALTER COLUMN event_kind SET NOT NULL;
ALTER TABLE crm_stage_history ALTER COLUMN time_quality SET NOT NULL;
ALTER TABLE crm_stage_history ALTER COLUMN recorded_at SET NOT NULL;

ALTER TABLE enquiries ADD COLUMN IF NOT EXISTS stage_time_quality TEXT NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE enquiries DROP CONSTRAINT IF EXISTS enquiries_stage_time_quality_check;
ALTER TABLE enquiries ADD CONSTRAINT enquiries_stage_time_quality_check
  CHECK (stage_time_quality IN ('OBSERVED', 'UNKNOWN'));

ALTER TABLE crm_activities ADD COLUMN IF NOT EXISTS contact_outcome TEXT;
ALTER TABLE crm_activities ADD COLUMN IF NOT EXISTS direction TEXT;
ALTER TABLE crm_activities ADD COLUMN IF NOT EXISTS demo_id UUID;
ALTER TABLE crm_activities ADD COLUMN IF NOT EXISTS proposal_version_id UUID;
ALTER TABLE crm_activities DROP CONSTRAINT IF EXISTS crm_activities_contact_outcome_check;
ALTER TABLE crm_activities ADD CONSTRAINT crm_activities_contact_outcome_check
  CHECK (contact_outcome IS NULL OR contact_outcome IN ('CONNECTED', 'SENT', 'RECEIVED', 'NO_ANSWER', 'UNKNOWN', 'NOT_APPLICABLE'));
ALTER TABLE crm_activities DROP CONSTRAINT IF EXISTS crm_activities_direction_check;
ALTER TABLE crm_activities ADD CONSTRAINT crm_activities_direction_check
  CHECK (direction IS NULL OR direction IN ('INBOUND', 'OUTBOUND', 'INTERNAL'));

DO $$ BEGIN
  ALTER TABLE crm_activities
    ADD CONSTRAINT crm_activities_demo_fk FOREIGN KEY (demo_id) REFERENCES crm_demos(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE crm_activities
    ADD CONSTRAINT crm_activities_proposal_version_fk FOREIGN KEY (proposal_version_id) REFERENCES crm_proposal_versions(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE crm_demos ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE crm_demos ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE crm_demos ADD COLUMN IF NOT EXISTS no_show_at TIMESTAMPTZ;

ALTER TABLE crm_tasks ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;

-- Invalid designations are review findings. They are not silently kept as actionable work.
INSERT INTO crm_review_queue (enquiry_id, reason)
SELECT e.id, 'INVALID_NEXT_ACTION'
FROM enquiries e
WHERE e.next_action_task_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM crm_tasks t
    WHERE t.id = e.next_action_task_id
      AND t.enquiry_id = e.id
      AND t.status IN ('OPEN', 'IN_PROGRESS')
  )
  AND NOT EXISTS (
    SELECT 1 FROM crm_review_queue q
    WHERE q.enquiry_id = e.id AND q.reason = 'INVALID_NEXT_ACTION' AND q.status = 'OPEN'
  );

UPDATE enquiries e
SET next_action_task_id = NULL
WHERE e.next_action_task_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM crm_tasks t
    WHERE t.id = e.next_action_task_id
      AND t.enquiry_id = e.id
      AND t.status IN ('OPEN', 'IN_PROGRESS')
  );

CREATE OR REPLACE FUNCTION crm_tasks_bump_version() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.row_version IS NOT DISTINCT FROM OLD.row_version THEN
    NEW.row_version := OLD.row_version + 1;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS crm_tasks_bump_version ON crm_tasks;
CREATE TRIGGER crm_tasks_bump_version
BEFORE UPDATE ON crm_tasks
FOR EACH ROW EXECUTE FUNCTION crm_tasks_bump_version();

CREATE OR REPLACE FUNCTION crm_touch_designated_follow_up() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'UPDATE'
     AND OLD.due_at IS NOT DISTINCT FROM NEW.due_at
     AND OLD.status IS NOT DISTINCT FROM NEW.status THEN
    RETURN NULL;
  END IF;
  UPDATE enquiries
  SET updated_at = now()
  WHERE next_action_task_id = NEW.id;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS crm_tasks_project_follow_up ON crm_tasks;
CREATE TRIGGER crm_tasks_project_follow_up
AFTER INSERT OR UPDATE OF due_at, status ON crm_tasks
FOR EACH ROW EXECUTE FUNCTION crm_touch_designated_follow_up();

CREATE OR REPLACE FUNCTION crm_enforce_next_action() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  task_enquiry UUID;
  task_status TEXT;
BEGIN
  IF NEW.next_action_task_id IS NULL THEN
    RETURN NULL;
  END IF;
  SELECT enquiry_id, status INTO task_enquiry, task_status
  FROM crm_tasks WHERE id = NEW.next_action_task_id;
  IF task_enquiry IS DISTINCT FROM NEW.id OR task_status NOT IN ('OPEN', 'IN_PROGRESS') THEN
    RAISE EXCEPTION 'designated next action must be an open task on this enquiry';
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS enquiries_next_action_guard ON enquiries;
CREATE CONSTRAINT TRIGGER enquiries_next_action_guard
AFTER INSERT OR UPDATE OF next_action_task_id ON enquiries
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION crm_enforce_next_action();

CREATE OR REPLACE FUNCTION crm_enforce_task_designation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM enquiries e
    WHERE e.next_action_task_id = NEW.id
      AND (NEW.enquiry_id IS DISTINCT FROM e.id OR NEW.status NOT IN ('OPEN', 'IN_PROGRESS'))
  ) THEN
    RAISE EXCEPTION 'designated next action must be an open task on this enquiry';
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS crm_tasks_designation_guard ON crm_tasks;
CREATE CONSTRAINT TRIGGER crm_tasks_designation_guard
AFTER UPDATE OF enquiry_id, status ON crm_tasks
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION crm_enforce_task_designation();

CREATE TABLE IF NOT EXISTS crm_pilots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  enquiry_id UUID NOT NULL REFERENCES enquiries(id) ON DELETE RESTRICT,
  status TEXT NOT NULL CHECK (status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
  planned_start_at TIMESTAMPTZ,
  planned_end_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  objective TEXT,
  success_criteria TEXT,
  result TEXT,
  decision_notes TEXT,
  created_by UUID,
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (planned_end_at IS NULL OR planned_start_at IS NULL OR planned_end_at > planned_start_at),
  CHECK (
    (status = 'PLANNED' AND started_at IS NULL AND completed_at IS NULL AND cancelled_at IS NULL)
    OR (status = 'ACTIVE' AND started_at IS NOT NULL AND completed_at IS NULL AND cancelled_at IS NULL)
    OR (status = 'COMPLETED' AND started_at IS NOT NULL AND completed_at IS NOT NULL AND cancelled_at IS NULL)
    OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND completed_at IS NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS crm_pilots_one_open
  ON crm_pilots (enquiry_id)
  WHERE status IN ('PLANNED', 'ACTIVE');

ALTER TABLE crm_activities ADD COLUMN IF NOT EXISTS pilot_id UUID;
DO $$ BEGIN
  ALTER TABLE crm_activities
    ADD CONSTRAINT crm_activities_pilot_fk FOREIGN KEY (pilot_id) REFERENCES crm_pilots(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

INSERT INTO crm_stage_definitions (code, label, sort_order, entry_requirements)
VALUES ('PILOT', 'Pilot', 70, '{"requires_active_pilot": true}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  entry_requirements = crm_stage_definitions.entry_requirements || EXCLUDED.entry_requirements;

INSERT INTO crm_stage_edges (from_code, to_code) VALUES
  ('PROPOSAL', 'PILOT'),
  ('NEGOTIATION', 'PILOT'),
  ('PILOT', 'PROPOSAL'),
  ('PILOT', 'NEGOTIATION')
ON CONFLICT DO NOTHING;

ALTER TABLE crm_stage_edges ADD COLUMN IF NOT EXISTS requires_reason BOOLEAN NOT NULL DEFAULT false;
UPDATE crm_stage_edges
SET requires_reason = true
WHERE from_code = 'PILOT' AND to_code IN ('PROPOSAL', 'NEGOTIATION') AND requires_reason = false;

ALTER TABLE crm_review_queue ADD COLUMN IF NOT EXISTS closure_id UUID;
ALTER TABLE crm_review_queue ADD COLUMN IF NOT EXISTS reviewed_by UUID;
ALTER TABLE crm_review_queue ADD COLUMN IF NOT EXISTS resolution_note TEXT;
ALTER TABLE crm_review_queue ADD COLUMN IF NOT EXISTS rule_version INTEGER;
DO $$ BEGIN
  ALTER TABLE crm_review_queue
    ADD CONSTRAINT crm_review_queue_closure_fk FOREIGN KEY (closure_id) REFERENCES crm_closures(id) ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS crm_review_open_enquiry_reason
  ON crm_review_queue (enquiry_id, reason, COALESCE(closure_id, '00000000-0000-0000-0000-000000000000'::uuid))
  WHERE status = 'OPEN' AND enquiry_id IS NOT NULL;

ALTER TABLE founders ADD COLUMN IF NOT EXISTS auth_user_id UUID;

CREATE TABLE IF NOT EXISTS crm_capture_epochs (
  id TEXT PRIMARY KEY,
  capture_started_at TIMESTAMPTZ NOT NULL,
  note TEXT NOT NULL
);
INSERT INTO crm_capture_epochs (id, capture_started_at, note)
SELECT 'sales_command_v1', now(), 'Observed stage, demo, proposal, pilot, and contact evidence captured from this migration forward.'
WHERE NOT EXISTS (SELECT 1 FROM crm_capture_epochs WHERE id = 'sales_command_v1');

CREATE TABLE IF NOT EXISTS crm_sales_command_policy (
  id TEXT PRIMARY KEY,
  rule_version INTEGER NOT NULL,
  high_value JSONB NOT NULL,
  stage_stale_days JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO crm_sales_command_policy (id, rule_version, high_value, stage_stale_days)
SELECT 'v1', 1, '{"INR":"100000.00"}'::jsonb,
  '{"NEW":2,"CONTACTED":7,"QUALIFIED":7,"DEMO":7,"PROPOSAL":14,"NEGOTIATION":14}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM crm_sales_command_policy WHERE id = 'v1');

CREATE OR REPLACE FUNCTION crm_school_sales_class(p enquiries)
RETURNS TEXT
LANGUAGE sql STABLE AS $$
  WITH acc AS (
    SELECT upper(btrim(vertical)) AS vertical
    FROM crm_accounts WHERE id = p.account_id
  ),
  tok AS (
    SELECT
      upper(btrim(COALESCE(p.product_vertical, ''))) AS product,
      upper(btrim(COALESCE(p.category, ''))) AS category
  )
  SELECT CASE
    WHEN p.account_id IS NOT NULL AND EXISTS (
      SELECT 1 FROM acc, tok
      WHERE acc.vertical = 'SCHOOL'
        AND (tok.product IN ('MEDICAL', 'RETAIL', 'OTHER') OR tok.category IN ('MEDICAL', 'RETAIL', 'OTHER'))
    ) THEN 'CONFLICT'
    WHEN p.account_id IS NOT NULL AND EXISTS (
      SELECT 1 FROM acc, tok
      WHERE acc.vertical <> 'SCHOOL'
        AND (tok.product IN ('SCHOOL', 'SCHOOLIMS') OR tok.category IN ('SCHOOL', 'SCHOOLIMS'))
    ) THEN 'CONFLICT'
    WHEN p.account_id IS NOT NULL AND EXISTS (SELECT 1 FROM acc WHERE vertical = 'SCHOOL') THEN 'SCHOOL'
    WHEN p.account_id IS NULL AND EXISTS (
      SELECT 1 FROM tok
      WHERE product IN ('SCHOOL', 'SCHOOLIMS') OR category IN ('SCHOOL', 'SCHOOLIMS')
    ) THEN 'SCHOOL'
    ELSE 'OTHER'
  END;
$$;

CREATE OR REPLACE FUNCTION crm_record_initial_stage_quality() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.stage_time_quality := 'OBSERVED';
  IF NEW.stage_entered_at IS NULL THEN
    NEW.stage_entered_at := COALESCE(NEW.created_at, now());
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS enquiries_initial_stage_quality ON enquiries;
CREATE TRIGGER enquiries_initial_stage_quality
BEFORE INSERT ON enquiries
FOR EACH ROW EXECUTE FUNCTION crm_record_initial_stage_quality();

CREATE OR REPLACE FUNCTION crm_record_initial_stage_history() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO crm_stage_history (
    enquiry_id, from_code, to_code, actor_id, entered_at, event_kind, time_quality, recorded_at
  ) VALUES (
    NEW.id, NULL, COALESCE(NEW.pipeline_stage_code, 'NEW'), NULL,
    COALESCE(NEW.created_at, NEW.stage_entered_at, now()), 'INITIAL', 'OBSERVED', now()
  );
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS enquiries_initial_stage_history ON enquiries;
CREATE TRIGGER enquiries_initial_stage_history
AFTER INSERT ON enquiries
FOR EACH ROW EXECUTE FUNCTION crm_record_initial_stage_history();

CREATE OR REPLACE FUNCTION ingest_website_enquiry(
  p_name TEXT,
  p_email TEXT,
  p_phone TEXT,
  p_message TEXT,
  p_product TEXT,
  p_website_source TEXT,
  p_channel_code TEXT,
  p_campaign TEXT,
  p_organization TEXT,
  p_budget_range TEXT
) RETURNS TABLE (id UUID, created_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  channel UUID;
  raw_product TEXT;
  vertical TEXT;
BEGIN
  IF char_length(trim(COALESCE(p_name, ''))) < 2 THEN
    RAISE EXCEPTION 'Name is required';
  END IF;
  IF NULLIF(trim(COALESCE(p_email, '')), '') IS NULL AND NULLIF(trim(COALESCE(p_phone, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Email or phone is required';
  END IF;
  raw_product := COALESCE(NULLIF(trim(p_product), ''), 'SchoolIMS');
  vertical := CASE
    WHEN upper(raw_product) IN ('SCHOOL', 'SCHOOLIMS') THEN 'SCHOOL'
    WHEN upper(raw_product) IN ('MEDICAL', 'RETAIL', 'OTHER') THEN upper(raw_product)
    ELSE left(raw_product, 40)
  END;
  SELECT c.id INTO channel FROM crm_acquisition_channels c
  WHERE c.code = COALESCE(NULLIF(trim(p_channel_code), ''), 'WEBSITE') AND c.archived_at IS NULL;
  RETURN QUERY
  INSERT INTO enquiries (
    name, email, phone, organization, message, budget_range, website_source, category, status,
    pipeline_stage_code, outcome, acquisition_channel_id, campaign_name,
    product_vertical, intake_queue, sales_model_version
  ) VALUES (
    trim(p_name),
    NULLIF(lower(trim(COALESCE(p_email, ''))), ''),
    NULLIF(trim(COALESCE(p_phone, '')), ''),
    NULLIF(trim(COALESCE(p_organization, '')), ''),
    NULLIF(trim(COALESCE(p_message, '')), ''),
    NULLIF(trim(COALESCE(p_budget_range, '')), ''),
    COALESCE(NULLIF(trim(p_website_source), ''), 'NEXSYRUS_WEBSITE'),
    raw_product,
    'NEW',
    'NEW',
    'OPEN',
    channel,
    NULLIF(trim(COALESCE(p_campaign, '')), ''),
    vertical,
    'UNASSIGNED_INTAKE',
    1
  )
  RETURNING enquiries.id, enquiries.created_at;
END $$;

CREATE OR REPLACE FUNCTION ingest_website_enquiry(
  p_name TEXT,
  p_email TEXT,
  p_phone TEXT,
  p_message TEXT,
  p_product TEXT,
  p_website_source TEXT,
  p_channel_code TEXT,
  p_campaign TEXT
) RETURNS TABLE (id UUID, created_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT * FROM ingest_website_enquiry(
    p_name, p_email, p_phone, p_message, p_product, p_website_source, p_channel_code, p_campaign, NULL, NULL
  );
END $$;

REVOKE ALL ON FUNCTION ingest_website_enquiry(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest_website_enquiry(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    GRANT EXECUTE ON FUNCTION ingest_website_enquiry(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO anon;
    REVOKE ALL ON FUNCTION ingest_website_enquiry(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    GRANT EXECUTE ON FUNCTION ingest_website_enquiry(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
    REVOKE ALL ON FUNCTION ingest_website_enquiry(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM authenticated;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_crm_stage_history_to_entered
  ON crm_stage_history (to_code, entered_at, enquiry_id);
CREATE INDEX IF NOT EXISTS idx_crm_closures_closed
  ON crm_closures (closed_at, outcome, enquiry_id);
CREATE INDEX IF NOT EXISTS idx_crm_closures_enquiry_closed
  ON crm_closures (enquiry_id, closed_at, created_at);
CREATE INDEX IF NOT EXISTS idx_crm_tasks_eligible_due
  ON crm_tasks (due_at, enquiry_id, id)
  WHERE status IN ('OPEN', 'IN_PROGRESS') AND task_type IN ('FOLLOW_UP', 'CALL', 'EMAIL', 'MEETING');
CREATE INDEX IF NOT EXISTS idx_crm_demos_completed
  ON crm_demos (completed_at, enquiry_id)
  WHERE completed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_crm_demos_booked
  ON crm_demos (created_at, enquiry_id);
CREATE INDEX IF NOT EXISTS idx_crm_proposal_versions_sent
  ON crm_proposal_versions (sent_recorded_at, proposal_id)
  WHERE sent_recorded_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_crm_pilots_status_end
  ON crm_pilots (status, planned_end_at, enquiry_id);
CREATE INDEX IF NOT EXISTS idx_crm_school_profiles_geo
  ON crm_school_profiles (state_normalized, district_normalized, account_id);

ALTER TABLE crm_pilots ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_demos ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_proposal_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_stage_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_closures ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_capture_epochs ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_sales_command_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON crm_pilots FROM PUBLIC;
REVOKE ALL ON crm_capture_epochs FROM PUBLIC;
REVOKE ALL ON crm_sales_command_policy FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON crm_pilots FROM anon;
    REVOKE ALL ON crm_demos FROM anon;
    REVOKE ALL ON crm_proposals FROM anon;
    REVOKE ALL ON crm_proposal_versions FROM anon;
    REVOKE ALL ON crm_tasks FROM anon;
    REVOKE ALL ON crm_stage_history FROM anon;
    REVOKE ALL ON crm_closures FROM anon;
    REVOKE ALL ON crm_activities FROM anon;
    REVOKE ALL ON crm_capture_epochs FROM anon;
    REVOKE ALL ON crm_sales_command_policy FROM anon;
    REVOKE ALL ON enquiries FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON crm_pilots FROM authenticated;
    REVOKE ALL ON crm_demos FROM authenticated;
    REVOKE ALL ON crm_proposals FROM authenticated;
    REVOKE ALL ON crm_proposal_versions FROM authenticated;
    REVOKE ALL ON crm_tasks FROM authenticated;
    REVOKE ALL ON crm_stage_history FROM authenticated;
    REVOKE ALL ON crm_closures FROM authenticated;
    REVOKE ALL ON crm_activities FROM authenticated;
    REVOKE ALL ON crm_capture_epochs FROM authenticated;
    REVOKE ALL ON crm_sales_command_policy FROM authenticated;
    REVOKE ALL ON enquiries FROM authenticated;
  END IF;
END $$;
