/**
 * Centralized Role-Based Access Control (RBAC) Architecture
 * Defines all system roles, permissions catalog, and role-to-permission mappings.
 */

const ROLES = {
  FOUNDER: 'FOUNDER',
  SUPER_ADMIN: 'SUPER_ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE',
  IMPLEMENTATION_MANAGER: 'IMPLEMENTATION_MANAGER',
  IMPLEMENTATION_EXECUTIVE: 'IMPLEMENTATION_EXECUTIVE',
  SUPPORT_MANAGER: 'SUPPORT_MANAGER',
  SUPPORT_EXECUTIVE: 'SUPPORT_EXECUTIVE',

  // Extensible future roles supported out of the box
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
  ACCOUNTS_MANAGER: 'ACCOUNTS_MANAGER',
  TECHNICAL_SUPPORT: 'TECHNICAL_SUPPORT',
  QA: 'QA',
  DEPLOYMENT_MANAGER: 'DEPLOYMENT_MANAGER',
  VIEW_ONLY_ADMIN: 'VIEW_ONLY_ADMIN',
};

const PERMISSIONS = {
  // School permissions
  SCHOOLS_READ_ALL: 'schools.read.all',
  SCHOOLS_READ_ASSIGNED: 'schools.read.assigned',
  SCHOOLS_CREATE: 'schools.create',
  SCHOOLS_UPDATE_ASSIGNED: 'schools.update.assigned',
  SCHOOLS_UPDATE_ALL: 'schools.update.all',
  SCHOOLS_ASSIGN: 'schools.assign',
  SCHOOLS_DELETE: 'schools.delete',

  // Data import permissions
  STUDENTS_READ_ASSIGNED: 'students.read.assigned',
  STUDENTS_IMPORT: 'students.import',
  STAFF_IMPORT: 'staff.import',
  TRANSPORT_IMPORT: 'transport.import',

  // Requirements permissions
  REQUIREMENTS_READ: 'requirements.read',
  REQUIREMENTS_CREATE: 'requirements.create',
  REQUIREMENTS_MANAGE: 'requirements.manage',

  // Complaints & Support permissions
  COMPLAINTS_READ: 'complaints.read',
  COMPLAINTS_CREATE: 'complaints.create',
  COMPLAINTS_UPDATE_ASSIGNED: 'complaints.update.assigned',
  COMPLAINTS_MANAGE: 'complaints.manage',

  // Onboarding checklist permissions
  CHECKLIST_READ: 'checklist.read',
  CHECKLIST_UPDATE: 'checklist.update',

  // Configurations permissions
  CONFIGS_READ: 'configs.read',
  CONFIGS_MODIFY: 'configs.modify',
  CONFIGS_APPROVE: 'configs.approve',

  // Builds & Deployments permissions
  BUILDS_READ: 'builds.read',
  BUILDS_TRIGGER: 'builds.trigger',
  BUILDS_APPROVE: 'builds.approve',
  DEPLOYMENTS_APPROVE: 'deployments.approve',

  // Users & Team management permissions
  USERS_CREATE: 'users.create',
  USERS_MANAGE: 'users.manage',
  USERS_READ_TEAM: 'users.read.team',

  // Audit & Analytics permissions
  AUDIT_READ: 'audit.read',
  ANALYTICS_READ: 'analytics.read',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS = {
  [ROLES.FOUNDER]: ALL_PERMISSIONS,
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,

  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.SCHOOLS_CREATE,
    PERMISSIONS.SCHOOLS_UPDATE_ASSIGNED,
    PERMISSIONS.SCHOOLS_ASSIGN,
    PERMISSIONS.USERS_READ_TEAM,
    PERMISSIONS.CHECKLIST_READ,
    PERMISSIONS.CHECKLIST_UPDATE,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_CREATE,
    PERMISSIONS.REQUIREMENTS_MANAGE,
    PERMISSIONS.COMPLAINTS_READ,
    PERMISSIONS.COMPLAINTS_CREATE,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.BUILDS_READ,
  ],

  [ROLES.SALES_EXECUTIVE]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.SCHOOLS_CREATE,
    PERMISSIONS.SCHOOLS_UPDATE_ASSIGNED,
    PERMISSIONS.STUDENTS_READ_ASSIGNED,
    PERMISSIONS.STUDENTS_IMPORT,
    PERMISSIONS.STAFF_IMPORT,
    PERMISSIONS.TRANSPORT_IMPORT,
    PERMISSIONS.CHECKLIST_READ,
    PERMISSIONS.CHECKLIST_UPDATE,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_CREATE,
    PERMISSIONS.COMPLAINTS_READ,
    PERMISSIONS.COMPLAINTS_CREATE,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.BUILDS_READ,
  ],

  [ROLES.IMPLEMENTATION_MANAGER]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.SCHOOLS_UPDATE_ASSIGNED,
    PERMISSIONS.SCHOOLS_ASSIGN,
    PERMISSIONS.USERS_READ_TEAM,
    PERMISSIONS.STUDENTS_READ_ASSIGNED,
    PERMISSIONS.STUDENTS_IMPORT,
    PERMISSIONS.STAFF_IMPORT,
    PERMISSIONS.TRANSPORT_IMPORT,
    PERMISSIONS.CHECKLIST_READ,
    PERMISSIONS.CHECKLIST_UPDATE,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_CREATE,
    PERMISSIONS.REQUIREMENTS_MANAGE,
    PERMISSIONS.COMPLAINTS_READ,
    PERMISSIONS.COMPLAINTS_CREATE,
    PERMISSIONS.COMPLAINTS_MANAGE,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.CONFIGS_MODIFY,
    PERMISSIONS.BUILDS_READ,
  ],

  [ROLES.IMPLEMENTATION_EXECUTIVE]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.SCHOOLS_UPDATE_ASSIGNED,
    PERMISSIONS.STUDENTS_READ_ASSIGNED,
    PERMISSIONS.STUDENTS_IMPORT,
    PERMISSIONS.STAFF_IMPORT,
    PERMISSIONS.TRANSPORT_IMPORT,
    PERMISSIONS.CHECKLIST_READ,
    PERMISSIONS.CHECKLIST_UPDATE,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_CREATE,
    PERMISSIONS.COMPLAINTS_READ,
    PERMISSIONS.COMPLAINTS_CREATE,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.BUILDS_READ,
  ],

  [ROLES.SUPPORT_MANAGER]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.USERS_READ_TEAM,
    PERMISSIONS.COMPLAINTS_READ,
    PERMISSIONS.COMPLAINTS_CREATE,
    PERMISSIONS.COMPLAINTS_MANAGE,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_CREATE,
    PERMISSIONS.REQUIREMENTS_MANAGE,
    PERMISSIONS.CONFIGS_READ,
  ],

  [ROLES.SUPPORT_EXECUTIVE]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.COMPLAINTS_READ,
    PERMISSIONS.COMPLAINTS_CREATE,
    PERMISSIONS.COMPLAINTS_UPDATE_ASSIGNED,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_CREATE,
    PERMISSIONS.CONFIGS_READ,
  ],

  // Extensible roles
  [ROLES.OPERATIONS_MANAGER]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.SCHOOLS_UPDATE_ASSIGNED,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.CHECKLIST_READ,
    PERMISSIONS.CHECKLIST_UPDATE,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_MANAGE,
    PERMISSIONS.COMPLAINTS_MANAGE,
    PERMISSIONS.ANALYTICS_READ,
  ],
  [ROLES.ACCOUNTS_MANAGER]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],
  [ROLES.TECHNICAL_SUPPORT]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.COMPLAINTS_READ,
    PERMISSIONS.COMPLAINTS_CREATE,
    PERMISSIONS.COMPLAINTS_UPDATE_ASSIGNED,
    PERMISSIONS.REQUIREMENTS_READ,
    PERMISSIONS.REQUIREMENTS_CREATE,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.BUILDS_READ,
  ],
  [ROLES.QA]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.BUILDS_READ,
    PERMISSIONS.CONFIGS_READ,
  ],
  [ROLES.DEPLOYMENT_MANAGER]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.BUILDS_READ,
    PERMISSIONS.BUILDS_TRIGGER,
    PERMISSIONS.BUILDS_APPROVE,
    PERMISSIONS.DEPLOYMENTS_APPROVE,
    PERMISSIONS.CONFIGS_READ,
  ],
  [ROLES.VIEW_ONLY_ADMIN]: [
    PERMISSIONS.SCHOOLS_READ_ASSIGNED,
    PERMISSIONS.CONFIGS_READ,
    PERMISSIONS.BUILDS_READ,
    PERMISSIONS.AUDIT_READ,
  ],
};

function normalizeRole(role) {
  if (!role || typeof role !== 'string') return '';
  return role.trim().toUpperCase();
}

function getRolePermissions(role) {
  const norm = normalizeRole(role);
  return ROLE_PERMISSIONS[norm] || [];
}

function hasPermission(role, permission) {
  const norm = normalizeRole(role);
  if (norm === ROLES.FOUNDER || norm === ROLES.SUPER_ADMIN) return true;
  const perms = ROLE_PERMISSIONS[norm] || [];
  return perms.includes(permission);
}

/**
 * Apply per-user GRANT / DENY overrides without changing the role catalogue.
 * Founder access is intentionally immutable and always includes every permission.
 */
function getEffectivePermissions(role, overrides = []) {
  const norm = normalizeRole(role);
  if (norm === ROLES.FOUNDER || norm === ROLES.SUPER_ADMIN) return [...ALL_PERMISSIONS];

  const effective = new Set(getRolePermissions(norm));
  for (const override of overrides) {
    if (!override || !ALL_PERMISSIONS.includes(override.permission)) continue;
    if (String(override.effect).toUpperCase() === 'DENY') effective.delete(override.permission);
    if (String(override.effect).toUpperCase() === 'GRANT') effective.add(override.permission);
  }
  return [...effective];
}

const MANAGER_ROLE_CHILDREN = {
  [ROLES.SALES_MANAGER]: [ROLES.SALES_EXECUTIVE],
  [ROLES.IMPLEMENTATION_MANAGER]: [ROLES.IMPLEMENTATION_EXECUTIVE],
  [ROLES.SUPPORT_MANAGER]: [ROLES.SUPPORT_EXECUTIVE, ROLES.TECHNICAL_SUPPORT],
  [ROLES.OPERATIONS_MANAGER]: [],
};

function canManageRole(managerRole, childRole) {
  const parent = normalizeRole(managerRole);
  const child = normalizeRole(childRole);
  if (parent === ROLES.FOUNDER || parent === ROLES.SUPER_ADMIN) {
    return child.endsWith('_MANAGER') || child === ROLES.VIEW_ONLY_ADMIN;
  }
  return (MANAGER_ROLE_CHILDREN[parent] || []).includes(child);
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ALL_PERMISSIONS,
  ROLE_PERMISSIONS,
  normalizeRole,
  getRolePermissions,
  getEffectivePermissions,
  hasPermission,
  MANAGER_ROLE_CHILDREN,
  canManageRole,
};
